[package]
name = "mandelbrot_interactive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Requires csfml and sfml packages

[dependencies]
sfml = "0.16"
#sfml = "0.21"
num_cpus = "1.13"
